// /** Declaration file generated by dts-gen */

// export class Input {
//     constructor(name: any, virtual: any);

//     close(): void;

//     parseMessage(bytes: any): any;

//     parseMtc(data: any): void;

// }

// export class Output {
//     constructor(name: any, virtual: any);

//     close(): void;

//     parseMessage(type: any, args: any): any;

//     send(type: any, args: any): void;

// }

// export function getInputs(): any;

// export function getOutputs(): any;

